### ISSUE TITLE
Failed to restart Home Assistant

### ISSUE THREAD

**Issue by bjarne007** [endor-force/home-assistant-garo-chargebox#4]
Failed to restart Home Assistant
The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: in "/config/configuration.yaml", line 23, column 23: Unable to read file /config/garo_chargebox/pkg_garo_chargebox.yaml.
i get this error if i add this text to /config/configuration.yaml
can you help me ?

homeassistant:

    packages:

      ### GARO CHARGEBOX ###
      garo_chargebox: !include garo_chargebox/pkg_garo_chargebox.yaml

**Comment by endor-force** [comment]
I hope you got it working by now
